channels:
- conda-forge
dependencies:
- aimsgb =1.1.0
- ase =3.22.1
- atomistics =0.1.16
- coverage
- codacy-coverage
- defusedxml =0.7.1
- h5py =3.10.0
- matplotlib-base =3.8.2
- mendeleev =0.14.0
- mp-api =0.39.4
- numpy =1.26.2
- pandas =2.1.3
- phonopy =2.21.0
- pint =0.22
- pyiron_base =0.6.13
- pylammpsmpi =0.2.10
- pyscal =2.10.18
- scikit-learn =1.3.2
- scipy =1.11.4
- seekpath =2.1.0
- spglib =2.1.0
- structuretoolkit =0.0.15
- python-blosc2  # required by pytables
