channels:
- conda-forge
dependencies:
- aimsgb =1.0.2
- ase =3.22.1
- atomistics =0.1.12
- defusedxml =0.7.0
- h5py =3.9.0
- matplotlib-base =3.8.2
- mendeleev =0.9.0
- mp-api =0.36.1
- numpy =1.26.0
- pandas =2.0.0
- phonopy =2.20.0
- pint =0.18
- pyiron_base =0.6.10
- pylammpsmpi =0.2.7
- pyscal =2.10.4
- scikit-learn =1.2.1
- scipy =1.11.1
- seekpath =1.9.5
- spglib =2.0.2
- structuretoolkit =0.0.14