channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx <6.1
- ase
- defusedxml
- future
- h5py
- matplotlib-base
- mendeleev
- numpy
- pandas
- phonopy
- pyiron_base
- pymatgen
- pyscal
- pyxtal
- scipy
- seekpath
- scikit-learn
- spglib
